# Generated by Django 3.0.8 on 2021-05-10 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a piece style (e.g. Prelude, Postlude, Interlude)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the piece', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('composer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Composer')),
                ('genre', models.ManyToManyField(help_text='Select a style for this piece', to='catalog.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='PieceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular piece across whole library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('f', 'Free'), ('a', 'Available'), ('r', 'Reserved')], default='f', help_text='Piece availability', max_length=1)),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Piece')),
            ],
        ),
    ]
